filebeat.inputs:
  - type: filestream
    id: system-logs
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log
    ignore_older: 0
    scan_frequency: 5s
processors:
  - dissect:
      tokenizer: "%{timestamp} src_ip=%{src_ip} dst_ip=%{dst_ip} action=%{action} bytes=%{bytes}"
      field: "message"
      target_prefix: ""
output.elasticsearch:
  hosts: ["https://elasticsearch:9200"]
  username: "elastic"
  password: "elastic"
  ssl.certificate_authorities: ["/usr/share/filebeat/config/certs/ca.crt"]
  ssl.verfication_mod: certificate
  ssl.certificate: "/usr/share/filebeat/config/certs/filebeat.crt"
  ssl.key: "/usr/share/filebeat/config/certs/filebeat.key"
setup.kibana:
  host: "https://kibana:5601"
  username: "elastic"
  password: "elastic"
  ssl.verification_mode: certificate
  ssl.certificate_authorities: ["/usr/share/filebeat/config/certs/ca.crt"]
  ssl.certificates: "/usr/share/filebeat/config/certs/filebeat.crt"
  ssl.key: "/usr/share/filebeat/config/certs/filebeat.key"
